### ISSUE TITLE
Cannot load web page

### ISSUE THREAD

**Issue by VonHirsch** [Falkirks/Volt#1]
Hi Falk, i'm sure this plugin is brilliant, i'm watching your video but I can't get an index.html file to load no matter what I try.  I'm putting a simple html file (index.html) in PocketMine-MP\volt\index.html.  I see the plugin loading perfectly when I start my server, then I goto the browser (http://localhost:7000) but nothing comes up, not even 404.

OS: Windows 7 x64
Pocketmine Version: 1.4-916
Volt: v3.0.2

Thanks!
![image](https://cloud.githubusercontent.com/assets/3280180/6838514/10696112-d331-11e4-84d6-1170e7d104a5.png)

**Comment by falkirks** [comment]
I can't reproduce the issue on my end. Do you think there could be another server on port 7000? Could you use a packet sniffer and try to diagnose the issue further?

**Comment by VonHirsch** [comment]
Ok thanks! I ran a netstat and when the server is running I see it listening on port 7000, when I shutdown the server the port is clear.

I also tried on port 8080 but that didn't work either.

![image](https://cloud.githubusercontent.com/assets/3280180/6838661/86b1efea-d333-11e4-955d-93f64efee8c3.png)

**Comment by Falkirks** [comment]
To avoid issues with PHP not releasing sockets I have to declare the socket as reusable. The may mean it won't show in `netstat` although I am not sure.

**Comment by falkirks** [comment]
Thanks. The issue is likely related to the HTTP protocol implementation. Is there anyway you could give me output from wireshark or tcpdump?

**Comment by VonHirsch** [comment]
possibly - or is there anyway to dump out any debug or error messages to the console by running the plugin via src?

**Comment by falkirks** [comment]
Not built in, sorry. You would need to add your own debugging to the code. Wireshark would be easier and would have more information about the request.

**Comment by VonHirsch** [comment]
Ok wireshark it is then!  I'll give it a shot

**Comment by VonHirsch** [comment]
I'm still downloading and installing wireshark, but I did a bit more testing.  I tried on a linux box and it worked as expected.  

This was interesting - I tried to access on windows (where its not working) with wget and this is what I see:

![image](https://cloud.githubusercontent.com/assets/3280180/6838808/e42e1b1a-d335-11e4-8b6d-0300f8fb9b93.png)

**Comment by VonHirsch** [comment]
Ok I have it for you - here: https://drive.google.com/file/d/0B8me7IxUcHd4MUtycXJRVkZILUk/view?usp=sharing

**Comment by falkirks** [comment]
@LouisBHirst That capture doesn't have any HTTP packets. I think you will need to capture on the loopback interface and not on wifi.

**Comment by PEMapModder** [comment]
Try using curl?

**Comment by falkirks** [comment]
Some browsers wouldn't load the page if the MIME type wasn't set correctly. This has been fixed.
