### ISSUE TITLE
How to load a dynamic page ?

### ISSUE THREAD

**Issue by guijun** [Falkirks/Volt#2]
thanks for this cool plugins.
I can load static pages including index.html.
but, I had spent a whole day to figure out the way to serve a dynamic page, e.g.:
http://localhost:7000/apicall?A=1&B=2&C=3

is't ok for you to bring us examples for Dynamic pages and example Helper?

**Comment by falkirks** [comment]
Dynamic pages don't have the right name. They should really be called static pages. You can set there content but you can't render them on a request specific basis. As for helpers, I haven't played with them myself, I just exposed the functionality for developers that want to.

**Comment by falkirks** [comment]
It has been a goal to work on an event based system for rendering pages as they come. This is somewhat hard to do as I need to get the request to bubble up safely from client thread to volt thread and then to the main thread, then all the way back again.
