### ISSUE TITLE
index.html

### ISSUE THREAD

**Issue by Gregor12** [Falkirks/Volt#3]
How can I make the index.html  on  Windows 8.1?

**Comment by Gregor12** [comment]
Can somebody help me?

**Comment by falkirks** [comment]
Just create the file in the `Volt` folder? Windows 8.1 might have issues connecting, that is another issue.

**Comment by Gregor12** [comment]
But in your Video in YouTube you've used a special link for the index.html

**Comment by falkirks** [comment]
I don't know what you mean.
