### ISSUE TITLE
Volt stops server

### ISSUE THREAD

**Issue by mcyanny** [Falkirks/Volt#6]
Volt stops server at reload and whenever someone connects to it. is this still working with 1.5? or 1.6?

> Warning: in_array() expects parameter 2 to be array, object given in phar://C:/Users/Yan/Desktop/Test Sever/plugins/Volt_v3.1.0.phar/src/volt/ServerTask.php on line 53
> zend_mm_heap corrupted
> bin\php\php.exe: Exit 1

@Falkirks  lol, sorry for tagging you I know its annoying

**Comment by falkirks** [comment]
@YanSoo123 I tried upgrading it for PHP 7, but I can't get the threading to work at this point

**Comment by Assblocker** [comment]
sad
